### PR TITLE
Shibboleth login

### PR DESCRIPTION
**Pull request by RoProducts**
Shibboleth login using currently the TestShib server,

Due to the fact that the idp for now is selected automatically (Piemonte) and not used alot of TODO's still exist. They need to be checked when using a real/production server.

### CODE REVIEW

**Comment by Gnafu** [comment]
The login page does not show.
Is there a "Logout" button?

**Comment by RoProducts** [comment]
I declared LoginActivity as the new "Launch" Activity in the manifest. This should be all what is necessary that the application launches it as entry point.

However, I had the same problem and it was necessary to define "LoginActivity" explicitly as launch activity in Android Studios Launch configuration. 
Yes, there is a Logout Button. When logged in in the MainActivity, select "Logout" from the very bottom of the nav drawer. In the subsequent LogoutFragment select "Logout" at the bottom.

**Comment by Gnafu** [comment]
Ok, so it is just a rebase issue, there are two LAUNCHER activities.
Change it so there is only one main activity.
The workflow should be:
 - User clicks on app icon
 - Splash screen is shown
 - Login page is shown (only if user isn't already logged in)

**Comment by RoProducts** [comment]
Okay, I updated the PR.

**Comment by Gnafu** [comment]
There are a couple of issues:
- On Login page: Close button does not work and user cannot use the "back" button to cancel login (also check the typo "chuidere")  -> You can just remove the close button as if the user does not want to log in and presses the "back" button, you can just close the app.
- On Menu: The entry "Logout" opens the account page: or it logs the user out (with confirm) or it is renamed "Account"
- The elaborazionestandard flavor does not work anymore (the login activity is missing): fix it by duplicating the Splash activity in both flavors and setting a different Intent on each ot them (ElaborazioneStandard -> MainActivity, ValutazioneDanno -> Login)

**Comment by RoProducts** [comment]
The issue to be not able to go "back" is due to the fact that Piemonte is auto selected as idp. I have designed the fragments that in LoginFragment, using "Cancel", the back button or the action bar arrow results in going "back" to the idp selection. This, temporarily, is no longer desired.
I adjusted this now that the cancel button and action bar arrow are hidden and the last option using the "back" button is now going to finish the activity.
I fixed the other two issues.

**Pull request merged**
