### PR TITLE
Valutazione danno form implementation

### PR DESCRIPTION
**Pull request by RoProducts**
Implementation for issue #16 and #17 

Note that you need to delete your local database file before installing.

The names_table for calcucation results for valutazione danno is called "names_table_val_danno". 
This is intended but not mandatory. For better compatibility with the standard flavour it could be called the same, but this would lead to inconsistencies within the data.
Hence I propose to distinguish also on database level between the flavours.

Several classes were divided into normal and val_danno flavour. They follow the same architecture in "val_danno" but do different things. See Elaborator and ElaborationResult for examples.

This lead to lots of new code which is actually old code, which has been "divided".
An exception is the ComputeFormActivity which is heavily used in this pull request for creating and managing the form for a "valutazione danno" calculation.
In the normal flavour the activity is no longer used but a dialog. Hence for clarity it could (and should) be moved to the "val_danno" flavour.

Note also some fixes for bugs in the standard elaboration flavour.

### CODE REVIEW

**Comment by Gnafu** [comment]
This pull request is base on an 8-days old branch, please rebase it so we can cleanly merge it.

Can you please explain why do we need to delete the local database before installing?
Thank you

**Comment by RoProducts** [comment]
Rebased.

If you have a local database which was used by the "normal elaboration" it won't work and give exceptions as the names_table is created but has another name.
You need to delete the file local_database.sqlite before running the first time the valutatione danno flavour. I think this was intended this way to separate between flavours.

**Comment by Gnafu** [comment]
Flavors are used to create two different application, so users can install both on their devices.
We decided to use a shared folder (hence a shared database file) to simplify the coding and the background file distribution.
Your choise to use a different table name ("names_table_val_danno") is correct.
The installation of one application should only benefit from the installation of the other one.

**Comment by RoProducts** [comment]
I did not know that both flavours may coexist at the same time.

Hence I changed the database scheme to use one database file for one flavour, this way a flavour uses one file and the data is not mixed up. So the names table does not change and is called "names_table" in both schemes, for easier understanding.

**Comment by Gnafu** [comment]
I had to fix the "elaborazioneStandard" flavor code to make it build

**Pull request merged**
